spring:
  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/app?createDatabaseIfNotExist=true
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
      temp:
        use_jdbc_metadata_defaults: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


auth-service:
  auth:
    access-token:
      validity: 300
    refresh-token:
      validity: 300